version: '3.7'
services:
  nuxt:
    image: node:16.18.0-alpine
    ports:
      - '${FRONTEND_PORT:-3000}:3000'
      - '24678:24678'
    volumes:
      - '.:/var/www/html'
    working_dir: '/var/www/html'
    command: /bin/sh -c "npm install && npm run start"
    networks:
      - front
networks:
  front:
    driver: bridge
